package com.twodevs.MergeIt.models.entities;
// Generated 26 mar. 2021 21:06:26 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ChecklistItems generated by hbm2java
 */
@Entity
@Table(name = "checklist_items")
public class ChecklistItem implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private Checklist checklist;
	private String name;
	private Boolean done;

	public ChecklistItem() {
	}

	public ChecklistItem(int id, Checklist checklist) {
		this.id = id;
		this.checklist = checklist;
	}

	public ChecklistItem(int id, Checklist checklist, String name, Boolean done) {
		this.id = id;
		this.checklist = checklist;
		this.name = name;
		this.done = done;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_checklist", nullable = false)
	public Checklist getChecklists() {
		return this.checklist;
	}

	public void setChecklists(Checklist checklist) {
		this.checklist = checklist;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "done")
	public Boolean getDone() {
		return this.done;
	}

	public void setDone(Boolean done) {
		this.done = done;
	}

}
