package com.twodevs.MergeIt.models.entities;
// Generated 26 mar. 2021 21:06:26 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * ChecklistItems generated by hbm2java
 */
@Entity
@Table(name = "checklist_items")
public class CheckListItem implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private CheckList checklist;
	private String name;
	private Boolean done;

	public CheckListItem() {
	}

	public CheckListItem(int id, CheckList checklist) {
		this.id = id;
		this.checklist = checklist;
	}

	public CheckListItem(int id, CheckList checklist, String name, Boolean done) {
		this.id = id;
		this.checklist = checklist;
		this.name = name;
		this.done = done;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_check_list", nullable = false)
	public CheckList getChecklist() {
		return this.checklist;
	}

	public void setChecklist(CheckList checklist) {
		this.checklist = checklist;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "done")
	public Boolean getDone() {
		return this.done;
	}

	public void setDone(Boolean done) {
		this.done = done;
	}

}
