package com.twodevs.MergeIt.models.entities;
// Generated 26 mar. 2021 18:34:00 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ChecklistItems generated by hbm2java
 */
@Entity
@Table(name = "checklist_items")
public class ChecklistItems implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private int idChecklist;
	private String name;
	private Boolean done;

	public ChecklistItems() {
	}

	public ChecklistItems(int id, int idChecklist) {
		this.id = id;
		this.idChecklist = idChecklist;
	}

	public ChecklistItems(int id, int idChecklist, String name, Boolean done) {
		this.id = id;
		this.idChecklist = idChecklist;
		this.name = name;
		this.done = done;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "id_checklist", nullable = false)
	public int getIdChecklist() {
		return this.idChecklist;
	}

	public void setIdChecklist(int idChecklist) {
		this.idChecklist = idChecklist;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "done")
	public Boolean getDone() {
		return this.done;
	}

	public void setDone(Boolean done) {
		this.done = done;
	}

}
