package com.twodevs.MergeIt.models.entities;
// Generated 25 mar. 2021 22:27:41 by Hibernate Tools 5.2.12.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Comentarios generated by hbm2java
 */
@Entity
@Table(name = "comentarios")
public class Comentarios implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private int idTarea;
	private int idUsuario;
	private String texto;
	private Date createdAt;
	private String color;
	private String checkList;
	private Boolean archivada;

	public Comentarios() {
	}

	public Comentarios(int id, int idTarea, int idUsuario, Date createdAt) {
		this.id = id;
		this.idTarea = idTarea;
		this.idUsuario = idUsuario;
		this.createdAt = createdAt;
	}

	public Comentarios(int id, int idTarea, int idUsuario, String texto, Date createdAt, String color, String checkList,
			Boolean archivada) {
		this.id = id;
		this.idTarea = idTarea;
		this.idUsuario = idUsuario;
		this.texto = texto;
		this.createdAt = createdAt;
		this.color = color;
		this.checkList = checkList;
		this.archivada = archivada;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "id_tarea", nullable = false)
	public int getIdTarea() {
		return this.idTarea;
	}

	public void setIdTarea(int idTarea) {
		this.idTarea = idTarea;
	}

	@Column(name = "id_usuario", nullable = false)
	public int getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(int idUsuario) {
		this.idUsuario = idUsuario;
	}

	@Column(name = "texto")
	public String getTexto() {
		return this.texto;
	}

	public void setTexto(String texto) {
		this.texto = texto;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created_at", nullable = false, length = 13)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Column(name = "color", length = 6)
	public String getColor() {
		return this.color;
	}

	public void setColor(String color) {
		this.color = color;
	}

	@Column(name = "CheckList")
	public String getCheckList() {
		return this.checkList;
	}

	public void setCheckList(String checkList) {
		this.checkList = checkList;
	}

	@Column(name = "archivada")
	public Boolean getArchivada() {
		return this.archivada;
	}

	public void setArchivada(Boolean archivada) {
		this.archivada = archivada;
	}

}
