package com.twodevs.MergeIt.models.entities;
// Generated 27 mar. 2021 19:54:19 by Hibernate Tools 5.2.12.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Comments generated by hbm2java
 */
@Entity
@Table(name = "comments")
public class Comment implements java.io.Serializable {

	private int id;
	private Task task;
	private int idUser;
	private String text;
	private Date createdAt;
	private Boolean archived;

	public Comment() {
	}

	public Comment(int id, Task task, int idUser, Date createdAt) {
		this.id = id;
		this.task = task;
		this.idUser = idUser;
		this.createdAt = createdAt;
	}

	public Comment(int id, Task task, int idUser, String text, Date createdAt, Boolean archived) {
		this.id = id;
		this.task = task;
		this.idUser = idUser;
		this.text = text;
		this.createdAt = createdAt;
		this.archived = archived;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_task", nullable = false)
	public Task getTasks() {
		return this.task;
	}

	public void setTasks(Task task) {
		this.task = task;
	}

	@Column(name = "id_user", nullable = false)
	public int getIdUser() {
		return this.idUser;
	}

	public void setIdUser(int idUser) {
		this.idUser = idUser;
	}

	@Column(name = "text")
	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created_at", nullable = false, length = 13)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Column(name = "archived")
	public Boolean getArchived() {
		return this.archived;
	}

	public void setArchived(Boolean archived) {
		this.archived = archived;
	}

}
