package com.twodevs.MergeIt.models.entities;
// Generated 25 mar. 2021 22:27:41 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Ficheros generated by hbm2java
 */
@Entity
@Table(name = "ficheros")
public class Ficheros implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private Tareas tareas;
	private String nombre;
	private String ruta;
	private String tipo;

	public Ficheros() {
	}

	public Ficheros(int id, Tareas tareas) {
		this.id = id;
		this.tareas = tareas;
	}

	public Ficheros(int id, Tareas tareas, String nombre, String ruta, String tipo) {
		this.id = id;
		this.tareas = tareas;
		this.nombre = nombre;
		this.ruta = ruta;
		this.tipo = tipo;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tarea", nullable = false)
	public Tareas getTareas() {
		return this.tareas;
	}

	public void setTareas(Tareas tareas) {
		this.tareas = tareas;
	}

	@Column(name = "nombre")
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "ruta")
	public String getRuta() {
		return this.ruta;
	}

	public void setRuta(String ruta) {
		this.ruta = ruta;
	}

	@Column(name = "tipo")
	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

}
