package com.twodevs.MergeIt.models.entities;
// Generated 25 mar. 2021 22:27:41 by Hibernate Tools 5.2.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Listas generated by hbm2java
 */
@Entity
@Table(name = "listas")
public class Listas implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private Proyectos proyectos;
	private String nombre;
	private Date createdAt;
	private Boolean archivada;
	private Set<Tareas> tareases = new HashSet<Tareas>(0);

	public Listas() {
	}

	public Listas(int id, Proyectos proyectos, Date createdAt) {
		this.id = id;
		this.proyectos = proyectos;
		this.createdAt = createdAt;
	}

	public Listas(int id, Proyectos proyectos, String nombre, Date createdAt, Boolean archivada, Set<Tareas> tareases) {
		this.id = id;
		this.proyectos = proyectos;
		this.nombre = nombre;
		this.createdAt = createdAt;
		this.archivada = archivada;
		this.tareases = tareases;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_proyecto", nullable = false)
	public Proyectos getProyectos() {
		return this.proyectos;
	}

	public void setProyectos(Proyectos proyectos) {
		this.proyectos = proyectos;
	}

	@Column(name = "nombre")
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created_at", nullable = false, length = 13)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Column(name = "archivada")
	public Boolean getArchivada() {
		return this.archivada;
	}

	public void setArchivada(Boolean archivada) {
		this.archivada = archivada;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "listas")
	public Set<Tareas> getTareases() {
		return this.tareases;
	}

	public void setTareases(Set<Tareas> tareases) {
		this.tareases = tareases;
	}

}
