package com.twodevs.MergeIt.models.entities;
// Generated 25 mar. 2021 22:27:41 by Hibernate Tools 5.2.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Proyectos generated by hbm2java
 */
@Entity
@Table(name = "proyectos")
public class Proyectos implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private Equipos equipos;
	private String nombre;
	private Date createdAt;
	private Set<Listas> listases = new HashSet<Listas>(0);

	public Proyectos() {
	}

	public Proyectos(int id, Equipos equipos, Date createdAt) {
		this.id = id;
		this.equipos = equipos;
		this.createdAt = createdAt;
	}

	public Proyectos(int id, Equipos equipos, String nombre, Date createdAt, Set<Listas> listases) {
		this.id = id;
		this.equipos = equipos;
		this.nombre = nombre;
		this.createdAt = createdAt;
		this.listases = listases;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_equipo", nullable = false)
	public Equipos getEquipos() {
		return this.equipos;
	}

	public void setEquipos(Equipos equipos) {
		this.equipos = equipos;
	}

	@Column(name = "nombre")
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created_at", nullable = false, length = 13)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "proyectos")
	public Set<Listas> getListases() {
		return this.listases;
	}

	public void setListases(Set<Listas> listases) {
		this.listases = listases;
	}

}
