package com.twodevs.MergeIt.models.entities;
// Generated 25 mar. 2021 22:27:41 by Hibernate Tools 5.2.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tareas generated by hbm2java
 */
@Entity
@Table(name = "tareas")
public class Tareas implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private Listas listas;
	private String nombre;
	private String descripcion;
	private Date createdAt;
	private String color;
	private String checkList;
	private Boolean archivada;
	private Set<Ficheros> ficheroses = new HashSet<Ficheros>(0);

	public Tareas() {
	}

	public Tareas(int id, Listas listas, Date createdAt) {
		this.id = id;
		this.listas = listas;
		this.createdAt = createdAt;
	}

	public Tareas(int id, Listas listas, String nombre, String descripcion, Date createdAt, String color,
			String checkList, Boolean archivada, Set<Ficheros> ficheroses) {
		this.id = id;
		this.listas = listas;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.createdAt = createdAt;
		this.color = color;
		this.checkList = checkList;
		this.archivada = archivada;
		this.ficheroses = ficheroses;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_lista", nullable = false)
	public Listas getListas() {
		return this.listas;
	}

	public void setListas(Listas listas) {
		this.listas = listas;
	}

	@Column(name = "nombre")
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "descripcion")
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created_at", nullable = false, length = 13)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Column(name = "color", length = 6)
	public String getColor() {
		return this.color;
	}

	public void setColor(String color) {
		this.color = color;
	}

	@Column(name = "CheckList")
	public String getCheckList() {
		return this.checkList;
	}

	public void setCheckList(String checkList) {
		this.checkList = checkList;
	}

	@Column(name = "archivada")
	public Boolean getArchivada() {
		return this.archivada;
	}

	public void setArchivada(Boolean archivada) {
		this.archivada = archivada;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tareas")
	public Set<Ficheros> getFicheroses() {
		return this.ficheroses;
	}

	public void setFicheroses(Set<Ficheros> ficheroses) {
		this.ficheroses = ficheroses;
	}

}
