package com.twodevs.MergeIt.models.entities;
// Generated 26 mar. 2021 18:34:00 by Hibernate Tools 5.2.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tasks generated by hbm2java
 */
@Entity
@Table(name = "tasks")
public class Tasks implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private Lists lists;
	private String name;
	private String description;
	private Date createdAt;
	private String color;
	private String checkList;
	private Boolean archivada;
	private Set<Files> fileses = new HashSet<Files>(0);

	public Tasks() {
	}

	public Tasks(int id, Lists lists, Date createdAt) {
		this.id = id;
		this.lists = lists;
		this.createdAt = createdAt;
	}

	public Tasks(int id, Lists lists, String name, String description, Date createdAt, String color, String checkList,
			Boolean archivada, Set<Files> fileses) {
		this.id = id;
		this.lists = lists;
		this.name = name;
		this.description = description;
		this.createdAt = createdAt;
		this.color = color;
		this.checkList = checkList;
		this.archivada = archivada;
		this.fileses = fileses;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_list", nullable = false)
	public Lists getLists() {
		return this.lists;
	}

	public void setLists(Lists lists) {
		this.lists = lists;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created_at", nullable = false, length = 13)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Column(name = "color", length = 6)
	public String getColor() {
		return this.color;
	}

	public void setColor(String color) {
		this.color = color;
	}

	@Column(name = "CheckList")
	public String getCheckList() {
		return this.checkList;
	}

	public void setCheckList(String checkList) {
		this.checkList = checkList;
	}

	@Column(name = "archivada")
	public Boolean getArchivada() {
		return this.archivada;
	}

	public void setArchivada(Boolean archivada) {
		this.archivada = archivada;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tasks")
	public Set<Files> getFileses() {
		return this.fileses;
	}

	public void setFileses(Set<Files> fileses) {
		this.fileses = fileses;
	}

}
