package com.twodevs.MergeIt.models.entities;
// Generated 25 mar. 2021 22:27:41 by Hibernate Tools 5.2.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Usuarios generated by hbm2java
 */
@Entity
@Table(name = "usuarios")
public class Usuarios implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private String username;
	private String password;
	private String email;
	private String nombre;
	private String apellidos;
	private Date fechaRegistro;
	private Set<Equipos> equiposes = new HashSet<Equipos>(0);

	public Usuarios() {
	}

	public Usuarios(int id) {
		this.id = id;
	}

	public Usuarios(int id, String username, String password, String email, String nombre, String apellidos,
			Date fechaRegistro, Set<Equipos> equiposes) {
		this.id = id;
		this.username = username;
		this.password = password;
		this.email = email;
		this.nombre = nombre;
		this.apellidos = apellidos;
		this.fechaRegistro = fechaRegistro;
		this.equiposes = equiposes;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "username")
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password")
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "email")
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "nombre")
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "apellidos")
	public String getApellidos() {
		return this.apellidos;
	}

	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_registro", length = 13)
	public Date getFechaRegistro() {
		return this.fechaRegistro;
	}

	public void setFechaRegistro(Date fechaRegistro) {
		this.fechaRegistro = fechaRegistro;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "equipos_usuarios", joinColumns = {
			@JoinColumn(name = "id_usuario", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "id_equipo", nullable = false, updatable = false) })
	public Set<Equipos> getEquiposes() {
		return this.equiposes;
	}

	public void setEquiposes(Set<Equipos> equiposes) {
		this.equiposes = equiposes;
	}

}
